name: Nintendo Ticket

on:
  schedule:
    - cron: '*/5 * * * *' # 5분마다 무조건 실행
  workflow_dispatch: # 내가 버튼 눌러서 강제 실행하는 옵션

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 코드 가져오기
        uses: actions/checkout@v3

      - name: 파이썬 세팅하기
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 필요한 패키지(requests) 설치
        run: pip install -r requirements.txt

      - name: 파이썬 스크립트 실행!
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          NINTENDO_COOKIE: ${{ secrets.NINTENDO_COOKIE }}
          NINTENDO_XSRF: ${{ secrets.NINTENDO_XSRF }}
        run: python main.py
